/* eslint-disable @next/next/no-img-element -- The existing client masters are
   already exported at their intended editorial crops; no derivative asset is
   generated by this page. */
"use client";

import Link from "next/link";
import {
  useEffect,
  useState,
  type CSSProperties,
  type KeyboardEvent,
} from "react";
import type { TranslationKey } from "../../lib/i18n/dictionaries";
import { useI18n } from "../../lib/i18n/I18nProvider";
import LocalizedPrice from "./LocalizedPrice";
import ClientCopyText from "./ClientCopyText";
import {
  HOME_V9_ANATOMY,
  HOME_V9_ASSETS,
  HOME_V9_COPY,
} from "./HomeExperienceV9.content";
import styles from "./HomeExperienceV9.module.css";

export type HomeColorway = {
  slug: "rose-pale" | "lilas-bleu-clair" | "pourpre";
  nameKey: TranslationKey;
  descriptionKey: TranslationKey;
  image: string;
  width: number;
  height: number;
  position: string;
  priceCents: number;
  swatch: string;
};

type Props = {
  colorways: readonly HomeColorway[];
  commerceOpen: boolean;
};

function ArrowIcon({ direction = "right" }: { direction?: "right" | "down" }) {
  return (
    <svg
      aria-hidden="true"
      className={direction === "down" ? styles.arrowDown : styles.arrow}
      viewBox="0 0 24 24"
    >
      <path d="M4 12h15M14 6l6 6-6 6" />
    </svg>
  );
}

export default function HomeExperienceV9({ colorways, commerceOpen }: Props) {
  const { t } = useI18n();
  const [activeIndex, setActiveIndex] = useState(() => {
    const pourpreIndex = colorways.findIndex(
      (colorway) => colorway.slug === HOME_V9_COPY.productSlug,
    );
    return pourpreIndex >= 0 ? pourpreIndex : 0;
  });
  const active = colorways[activeIndex] ?? colorways[0];

  useEffect(() => {
    if (
      window.self === window.top ||
      new URLSearchParams(window.location.search).get("frontend-design") !==
        "round-4"
    ) {
      return;
    }
    window.parent.postMessage(
      { round: "round-4", type: "aj-luxury-preview-ready" },
      "*",
    );
  }, []);

  if (!active) return null;

  const heroProduct =
    colorways.find((colorway) => colorway.slug === "pourpre") ?? active;

  const moveBetweenColorways = (
    event: KeyboardEvent<HTMLButtonElement>,
    index: number,
  ) => {
    let nextIndex: number | null = null;
    if (event.key === "ArrowRight") nextIndex = (index + 1) % colorways.length;
    if (event.key === "ArrowLeft") {
      nextIndex = (index - 1 + colorways.length) % colorways.length;
    }
    if (event.key === "Home") nextIndex = 0;
    if (event.key === "End") nextIndex = colorways.length - 1;
    if (nextIndex === null) return;

    event.preventDefault();
    setActiveIndex(nextIndex);
    document.getElementById(`home-colorway-${colorways[nextIndex]?.slug}`)?.focus();
  };

  return (
    <div className={styles.page}>
      <section
        className={styles.hero}
        data-aj-tete-seuil=""
        data-fd-id={HOME_V9_ANATOMY[0]}
        aria-labelledby="home-hero-title"
      >
        <div className={styles.heroCopy}>
          <h1
            className={styles.heroTitle}
            data-fd-editable="text"
            data-fd-id="text-hero-title"
            id="home-hero-title"
          >
            <span>{HOME_V9_COPY.heroLineOne}</span>
            <span>
              {HOME_V9_COPY.heroLineTwoLead}{" "}
              <em>{HOME_V9_COPY.heroLineTwoAccent}</em>
            </span>
          </h1>
          <div className={styles.heroOffer} data-fd-id="offer-hero-apollon">
            <p className={styles.heroModel}>{t("home.apollonEyebrow")}</p>
            <p className={styles.heroPrice}>
              <LocalizedPrice amountCents={heroProduct.priceCents} />
            </p>
            {!commerceOpen && (
              <p className={styles.heroSaleState}>{t("product.priceLabel")}</p>
            )}
            <Link
              className={`${styles.textLink} ${styles.heroCta}`}
              data-fd-id="btn-hero-apollon"
              href="/products/pourpre"
            >
              <span>{t("shop.discover")} Apollon</span>
              <ArrowIcon />
            </Link>
          </div>
        </div>

        <figure className={styles.heroMedia}>
          <img
            src={HOME_V9_ASSETS.hero}
            alt="AJ Luxury — détail d’Apollon Pourpre Impérial"
            width={1731}
            height={2600}
            fetchPriority="high"
            decoding="async"
          />
        </figure>
      </section>

      <section
        className={styles.colorways}
        data-fd-id={HOME_V9_ANATOMY[1]}
        id="apollon"
        aria-labelledby="home-apollon-title"
      >
        <div className={styles.colorwayCopy}>
          <div className={styles.sectionHeading}>
            <h2 id="home-apollon-title">Apollon</h2>
            <p>{t("shop.intro").replace(/^Apollon est le premier modèle de la maison\.\s*/, "")}</p>
          </div>

          <div
            className={styles.tabs}
            role="tablist"
            aria-label={t("sequence.tablist")}
          >
            {colorways.map((colorway, index) => {
              const selected = index === activeIndex;
              return (
                <button
                  aria-controls="home-colorway-panel"
                  aria-selected={selected}
                  className={selected ? styles.tabActive : styles.tab}
                  id={`home-colorway-${colorway.slug}`}
                  key={colorway.slug}
                  onClick={() => setActiveIndex(index)}
                  onKeyDown={(event) => moveBetweenColorways(event, index)}
                  role="tab"
                  style={{ "--colorway": colorway.swatch } as CSSProperties}
                  tabIndex={selected ? 0 : -1}
                  type="button"
                >
                  {t(colorway.nameKey)}
                </button>
              );
            })}
          </div>

          <div
            aria-labelledby={`home-colorway-${active.slug}`}
            className={styles.colorwayDetails}
            id="home-colorway-panel"
            role="tabpanel"
          >
            <h3>{t(active.nameKey)}</h3>
            <p>{t(active.descriptionKey)}</p>
            <div className={styles.productFacts}>
              <span className={styles.price}>
                <LocalizedPrice amountCents={active.priceCents} />
              </span>
              {!commerceOpen && (
                <span className={styles.saleState}>{t("product.priceLabel")}</span>
              )}
              <span className={styles.sizes}>
                {t("home.sizes")} — S · M · L · XL
              </span>
            </div>
            <Link className={styles.textLink} href={`/products/${active.slug}`}>
              <span>{t("shop.discover")}</span>
              <ArrowIcon />
            </Link>
          </div>
        </div>

        <div
          className={styles.colorwayMedia}
          data-fd-id="media-colorway-active"
          key={active.slug}
          style={{ "--media-position": active.position } as CSSProperties}
        >
          <figure className={styles.colorwayFrame}>
            <img
              src={active.image}
              alt={t("sequence.bodyAlt").replace("{color}", t(active.nameKey))}
              width={active.width}
              height={active.height}
              loading="lazy"
              decoding="async"
            />
          </figure>
        </div>
      </section>

      <section
        className={styles.material}
        data-fd-id={HOME_V9_ANATOMY[2]}
        aria-labelledby="home-material-title"
      >
        <figure className={styles.materialMedia}>
          <img
            src={HOME_V9_ASSETS.material}
            alt={t("product.feature.5")}
            width={2000}
            height={1331}
            loading="eager"
            decoding="async"
          />
        </figure>
        <div className={styles.materialCopy}>
          <p className={styles.materialLabel}>Apollon · Rose Velours</p>
          <h2 id="home-material-title">{t("product.feature.5")}</h2>
          <dl className={styles.composition}>
            <div>
              <dt>94 %</dt>
              <dd>{t("home.materialModal")}</dd>
            </div>
            <div>
              <dt>6 %</dt>
              <dd>{t("home.materialElastane")}</dd>
            </div>
          </dl>
          <Link className={styles.textLink} href="/shop">
            <span>{t("home.viewBoutique")}</span>
            <ArrowIcon />
          </Link>
        </div>
      </section>

      <section
        className={styles.campaignClosing}
        data-fd-id={HOME_V9_ANATOMY[3]}
        aria-labelledby="home-closing-title"
      >
        <figure
          className={styles.campaignMedia}
          data-fd-id="media-campaign-lilac"
        >
          <picture>
            <source
              media="(max-width: 760px)"
              srcSet={HOME_V9_ASSETS.campaign.mobile}
            />
            <source
              media="(max-width: 1100px)"
              srcSet={HOME_V9_ASSETS.campaign.tablet}
            />
            <img
              src={HOME_V9_ASSETS.campaign.desktop}
              alt="AJ Luxury — Alex et Jérémy portent Apollon Lilas Céleste"
              width={1484}
              height={2229}
              loading="eager"
              decoding="async"
            />
          </picture>
        </figure>
        <div className={styles.closingCopy}>
          <p className={styles.closingLabel}>Apollon · Lilas Céleste</p>
          <h2
            data-fd-editable="text"
            data-fd-id="text-closing-apollon"
            id="home-closing-title"
          >
            <ClientCopyText copyKey={HOME_V9_COPY.closingCopyKey} />
          </h2>
          <div className={styles.closingLinks}>
            <Link
              className={styles.textLink}
              data-fd-id="btn-closing-shop"
              href="/shop"
            >
              <span>{t("home.viewBoutique")}</span>
              <ArrowIcon />
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
