/* eslint-disable @next/next/no-img-element -- The existing client masters are
   already exported at their intended editorial crops; no derivative asset is
   generated by this page. */
"use client";

import Link from "next/link";
import {
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type MouseEvent,
} from "react";
import type { TranslationKey } from "../../lib/i18n/dictionaries";
import { useI18n } from "../../lib/i18n/I18nProvider";
import LocalizedPrice from "./LocalizedPrice";
import ClientCopyText from "./ClientCopyText";
import styles from "./HomeExperienceV9.module.css";

export type HomeColorway = {
  slug: "rose-pale" | "lilas-bleu-clair" | "pourpre";
  nameKey: TranslationKey;
  descriptionKey: TranslationKey;
  image: string;
  width: number;
  height: number;
  position: string;
  priceCents: number;
  swatch: string;
};

type Props = {
  colorways: readonly HomeColorway[];
  commerceOpen: boolean;
};

function ArrowIcon({ direction = "right" }: { direction?: "right" | "down" }) {
  return (
    <svg
      aria-hidden="true"
      className={direction === "down" ? styles.arrowDown : styles.arrow}
      viewBox="0 0 24 24"
    >
      <path d="M4 12h15M14 6l6 6-6 6" />
    </svg>
  );
}

export default function HomeExperienceV9({ colorways, commerceOpen }: Props) {
  const { t } = useI18n();
  const [activeIndex, setActiveIndex] = useState(1);
  const active = colorways[activeIndex] ?? colorways[0];

  if (!active) return null;

  const moveToApollon = (event: MouseEvent<HTMLAnchorElement>) => {
    const section = document.getElementById("apollon");
    if (!section) return;
    event.preventDefault();
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    section.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "start" });
    window.history.replaceState(null, "", "#apollon");
  };

  const moveBetweenColorways = (
    event: KeyboardEvent<HTMLButtonElement>,
    index: number,
  ) => {
    let nextIndex: number | null = null;
    if (event.key === "ArrowRight") nextIndex = (index + 1) % colorways.length;
    if (event.key === "ArrowLeft") {
      nextIndex = (index - 1 + colorways.length) % colorways.length;
    }
    if (event.key === "Home") nextIndex = 0;
    if (event.key === "End") nextIndex = colorways.length - 1;
    if (nextIndex === null) return;

    event.preventDefault();
    setActiveIndex(nextIndex);
    document.getElementById(`home-colorway-${colorways[nextIndex]?.slug}`)?.focus();
  };

  return (
    <div className={styles.page}>
      <section
        className={styles.hero}
        data-aj-tete-seuil=""
        aria-labelledby="home-hero-title"
      >
        <div className={styles.heroCopy}>
          <h1 className={styles.heroTitle} id="home-hero-title">
            <span>Reveal Your</span>
            <span>
              Inner <em>Beauty</em>
            </span>
          </h1>
          <p className={styles.heroModel}>{t("home.apollonEyebrow")}</p>
          <a className={styles.textLink} href="#apollon" onClick={moveToApollon}>
            <span>{t("hero.discover")} Apollon</span>
            <ArrowIcon direction="down" />
          </a>
        </div>

        <figure className={styles.heroMedia}>
          <picture>
            <source
              media="(max-width: 720px)"
              srcSet="/images/client/hero-v6-portrait-720x934-poster.webp"
            />
            <source
              media="(max-width: 1100px)"
              srcSet="/images/client/hero-v6-tablet-1440x810-poster.webp"
            />
            <img
              src="/images/client/hero-v6-xl-native-1920x1080-poster.webp"
              alt="AJ Luxury — Alex et Jérémy portent Apollon Lilas Céleste dans le décor architectural de la maison"
              width={1920}
              height={1080}
              fetchPriority="high"
              decoding="async"
            />
          </picture>
        </figure>
      </section>

      <section
        className={styles.colorways}
        id="apollon"
        aria-labelledby="home-apollon-title"
      >
        <div className={styles.colorwayCopy}>
          <div className={styles.sectionHeading}>
            <h2 id="home-apollon-title">Apollon</h2>
            <p>{t("shop.intro").replace(/^Apollon est le premier modèle de la maison\.\s*/, "")}</p>
          </div>

          <div
            className={styles.tabs}
            role="tablist"
            aria-label={t("sequence.tablist")}
          >
            {colorways.map((colorway, index) => {
              const selected = index === activeIndex;
              return (
                <button
                  aria-controls="home-colorway-panel"
                  aria-selected={selected}
                  className={selected ? styles.tabActive : styles.tab}
                  id={`home-colorway-${colorway.slug}`}
                  key={colorway.slug}
                  onClick={() => setActiveIndex(index)}
                  onKeyDown={(event) => moveBetweenColorways(event, index)}
                  role="tab"
                  style={{ "--colorway": colorway.swatch } as CSSProperties}
                  tabIndex={selected ? 0 : -1}
                  type="button"
                >
                  {t(colorway.nameKey)}
                </button>
              );
            })}
          </div>

          <div
            aria-labelledby={`home-colorway-${active.slug}`}
            className={styles.colorwayDetails}
            id="home-colorway-panel"
            role="tabpanel"
          >
            <h3>{t(active.nameKey)}</h3>
            <p>{t(active.descriptionKey)}</p>
            <div className={styles.productFacts}>
              <span className={styles.price}>
                <LocalizedPrice amountCents={active.priceCents} />
              </span>
              {!commerceOpen && (
                <span className={styles.saleState}>{t("product.priceLabel")}</span>
              )}
              <span className={styles.sizes}>
                {t("home.sizes")} — S · M · L · XL
              </span>
            </div>
            <Link className={styles.textLink} href={`/products/${active.slug}`}>
              <span>{t("shop.discover")}</span>
              <ArrowIcon />
            </Link>
          </div>
        </div>

        <div
          className={styles.colorwayMedia}
          key={active.slug}
          style={{ "--media-position": active.position } as CSSProperties}
        >
          <figure className={styles.colorwayFrame}>
            <img
              src={active.image}
              alt={t("sequence.bodyAlt").replace("{color}", t(active.nameKey))}
              width={active.width}
              height={active.height}
              loading="lazy"
              decoding="async"
            />
          </figure>
        </div>
      </section>

      <section className={styles.material} aria-labelledby="home-material-title">
        <figure className={styles.materialMedia}>
          <img
            src="/images/client/raw/product-rose-detail.webp"
            alt={t("product.feature.5")}
            width={2000}
            height={1331}
            loading="lazy"
            decoding="async"
          />
        </figure>
        <div className={styles.materialCopy}>
          <h2 id="home-material-title">{t("home.apollonEyebrow")}</h2>
          <div className={styles.materialPrice}>
            <LocalizedPrice amountCents={colorways[0]?.priceCents ?? null} />
            {!commerceOpen && <span>{t("product.priceLabel")}</span>}
          </div>
          <p className={styles.materialSizes}>
            {t("home.sizes")} — S · M · L · XL
          </p>
          <dl className={styles.composition}>
            <div>
              <dt>94 %</dt>
              <dd>{t("home.materialModal")}</dd>
            </div>
            <div>
              <dt>6 %</dt>
              <dd>{t("home.materialElastane")}</dd>
            </div>
            <div>
              <dt className={styles.compositionText}>3,5 cm</dt>
              <dd>{t("product.feature.5")}</dd>
            </div>
          </dl>
          <Link className={styles.textLink} href="/shop">
            <span>{t("home.viewBoutique")}</span>
            <ArrowIcon />
          </Link>
        </div>
      </section>

      <section className={styles.editorial} aria-labelledby="home-editorial-title">
        <div className={styles.editorialCopy}>
          <p className={styles.editorialLabel}>{t("home.incarnationEyebrow")}</p>
          <h2 id="home-editorial-title">{t("story.lead")}</h2>
          <p className={styles.editorialStatement}>
            <ClientCopyText copyKey="brandStory" />
          </p>
          <div className={styles.editorialLinks}>
            <Link className={styles.textLink} href="/shop">
              <span>{t("home.viewBoutique")}</span>
              <ArrowIcon />
            </Link>
            <Link className={styles.textLink} href="/notre-histoire">
              <span>{t("home.discoverStory")}</span>
              <ArrowIcon />
            </Link>
          </div>
        </div>

        <div className={styles.editorialMedia}>
          <figure className={styles.editorialMain}>
            <img
              src="/images/client/campaign-duo-pourpre.webp"
              alt="AJ Luxury — Alex et Jérémy portent Apollon Pourpre Impérial"
              width={2000}
              height={1882}
              loading="lazy"
              decoding="async"
            />
          </figure>
        </div>
      </section>
    </div>
  );
}
