import type { ProductSize } from "../products.ts";

const MODEL_CODE = "APO";

// Deliberately independent from the exported catalogue array: reference
// validation must not change if another module mutates catalogue input.
const referenceSizes = Object.freeze(["S", "M", "L", "XL"] as const);
const referenceSizeSet = new Set<string>(referenceSizes);

const colorCodes = {
  pourpre: "POU",
  "rose-pale": "ROS",
  "lilas-bleu-clair": "LIL",
} as const;

export type LaunchColorSlug = keyof typeof colorCodes;

export function isLaunchColorSlug(value: string): value is LaunchColorSlug {
  return Object.hasOwn(colorCodes, value);
}

export function isProductSize(value: string): value is ProductSize {
  return referenceSizeSet.has(value);
}

/**
 * Internal AJ Luxury reference. It is not an EAN or a public barcode.
 * The reference is generated by the application and never requested from the client.
 */
export function buildInternalVariantReference(
  colorSlug: LaunchColorSlug,
  size: ProductSize,
): string {
  if (!isLaunchColorSlug(colorSlug) || !isProductSize(size)) {
    throw new Error("Unsupported AJ Luxury launch variant.");
  }
  return `AJ-${MODEL_CODE}-${colorCodes[colorSlug]}-${size}`;
}

export function parseInternalVariantReference(reference: string): {
  colorSlug: LaunchColorSlug;
  size: ProductSize;
} | null {
  const match = /^AJ-APO-(POU|ROS|LIL)-(S|M|L|XL)$/.exec(reference);

  if (!match) {
    return null;
  }

  const colorSlug = Object.entries(colorCodes).find(
    ([, code]) => code === match[1],
  )?.[0];

  if (!colorSlug || !isLaunchColorSlug(colorSlug) || !isProductSize(match[2])) {
    return null;
  }

  return { colorSlug, size: match[2] };
}
