import type { ProductSize } from "../products.ts";
import {
  createApollonInternalReference,
  isLaunchProductSize,
  isLaunchProductSlug,
  parseApollonInternalReference,
  type LaunchProductSlug,
} from "./product-identifiers.ts";

export type LaunchColorSlug = LaunchProductSlug;
export type InternalReferenceSize = ProductSize;
export { createApollonInternalReference };

export function isLaunchColorSlug(value: string): value is LaunchColorSlug {
  return isLaunchProductSlug(value);
}

export function isProductSize(value: string): value is ProductSize {
  return isLaunchProductSize(value);
}

/**
 * Internal AJ Luxury reference. It is not an EAN or a public barcode.
 * The reference is generated by the application and never requested from the client.
 */
export function buildInternalVariantReference(
  colorSlug: LaunchColorSlug,
  size: ProductSize,
): string {
  if (!isLaunchColorSlug(colorSlug) || !isProductSize(size)) {
    throw new Error("Unsupported AJ Luxury launch variant.");
  }
  return createApollonInternalReference(colorSlug, size);
}

export function parseInternalVariantReference(reference: string): {
  colorSlug: LaunchColorSlug;
  size: ProductSize;
} | null {
  const parsed = parseApollonInternalReference(reference);
  return parsed
    ? { colorSlug: parsed.productSlug, size: parsed.size }
    : null;
}
